# input files
inputs:
  # PDF parameter inputs:  
  input file: newmin_pos_glw2nd_r19_Teq1.dat
  # input covariance matrix file (if used)
  cov input file: newmin_final_remin_out.dat
  # if true then read in covariance matrix and evaluate PDF errors
  readcov: False

#  output files
outputs:
  # label for output files
  label: test

basis pars:
  # If true then two term gluon parameterisation uesd
  g_second_term: True
  # if true and g_second_term=False then includes 7th Chebyshev for gluon
  g_cheb7: False
  # If true then delta_S+ set to that of sea
  asp_fix: True
  # If true thedelta_d=delta_u for d_V and u_V (need to set delta_d fixed or will crash!)
  dvd_eq_uvd: False

pdf pars:
  # use external LHAPDF grid as input 
  lhin: True
  # if true then use lhapdf grids for theory evaluation 
  # (for PDF pd fits can use parameterisation directly instead, otherwise has to be true)
  uselha: True
  # if lhin=true, name of set input
  PDFlabel_lhin: MSHT20nnlo_as118

pdf closure:
  # if true then scatters when doing direct PDF pd fit
  pdfscat: False
  # label of pseudodata used
  pdlabel: 'NNPDF40pch_gl_l0'
  #  if true then do direct fit to PDF pseudodata
  pdpdf: False

pseudodata flags:
  # if true then write pseudodata out to file
  pdout: False
  # if true then write pseudodata out to file
  pdin: False

fit pars:
  # Only use t0 for chi2i and chi2o in levmar (i.e. no derivative at all)
  t0_noderivin: True
  # run with fixed input parameters (override input card flags)
  fixpar: True
  # NNPDF theory id (211 = NNLO pch)
  theoryidi: 211
  # impose NNPDF positivity in fit
  nnpdf_pos: False
  # if true then impose 4.0 positivity constraint, if pos_const=True
  pos_40: True
  # if true impose weight to prefer delta_d > 0.25
  deld_const: False
  # if true then generates a replica from baseline dataset with seed irep
  pseud: False
  # irep number - also used when generating error grids
  irep: 0
  # NMC PD data - set covariance matrix to be diagonal
  nmcpd_diag: False
  # dataset flag - global, HERAonly, noHERA, noLHC
  dset_type: 'global'